BASE_URL = "https://api.brawlstars.com/v1"
URL_PLAYERS = BASE_URL + "/players"
URL_CLUBS = BASE_URL + "/clubs"
URL_RANKINGS = BASE_URL + "/rankings"
URL_BRAWLERS = BASE_URL + "/brawlers"
URL_EVENTS = BASE_URL + "/events/rotation"
